[features]
seeds = false
skip-lint = false
[programs.devnet]
deposit = "8qCGCh9UYRicNDoZzzjkjLvidj1asvnuvYUJu5KJbCL9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/professorcodegeek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 1000000
