[features]
seeds = false
skip-lint = false
[programs.devnet]
farmer_program = "5TNiwQX4cLvYtRp4vwhukHTrNt6MsK8URs6P98vsznQX"
farm_program = "94ceRzNSPEPDN2AA3ZQQ2KXAwzFtPxTcGkrqBZEf5syt"
tree_program = "GKUYrzV8pu6ZNvKG4KmEMMbMeqeSJGH1vQYgk9RuoYSR"
fruit_market_program = "8VQ8dQTWFFziNpFWgpuirGNji6Xp2jMbxnWYzfZmj8sP"

# Metaplex
# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Dex
# [[test.validator.clone]]
# address ="EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/professorcodegeek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 1000000
