[features]
seeds = false
skip-lint = false
[programs.devnet]
farmer_program = "9CWoSJWQZaNiZ83cqEer79u4MtZdfo8RRnspJcDnsZcu"
farm_program = "xFUDB75wmPfzua8VgnSLrnNH18Ve4xztakzfBVyURob"
tree_program = "8qxZgcFjdoJSwJYnvMMgR1ACyH24oFTBcaw8LSrAkiic"
fruit_market_program = "BdyXR2oKTEyeV8FRmRA2F7dxHjtkWeBtMEHqZPSQVuVd"

# Metaplex
# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Dex
# [[test.validator.clone]]
# address ="EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/professorcodegeek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 1000000
